class CAS:
    def __init__(self, cas_rn: int | str) -> None: ...
    def __format__(self, format_spec: str) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    @property
    def cas_string(self) -> str: ...
    @cas_string.setter
    def cas_string(self, cas_rn: str) -> None: ...
    @property
    def cas_integer(self) -> int: ...
    @cas_integer.setter
    def cas_integer(self, cas_rn: int) -> None: ...
    @property
    def check_digit(self) -> int: ...
    @check_digit.setter
    def check_digit(self, digit_to_test: int) -> None: ...
