name: Release

on:
  release:
    types: [published]

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    environment: pypi
    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        
      - name: Install dependencies
        run: uv sync --dev
        
      - name: Run tests before release
        run: uv run pytest -v
        
      - name: Build package
        run: uv build
        
      - name: Verify build
        run: |
          ls -la dist/
          uv run twine check dist/*
        
      - name: Smoke test (wheel)
        run: |
          WHEEL=$(ls dist/*.whl)
          uv run --isolated --no-project -p 3.12 --with "$WHEEL" python -c "from casregnum import CAS; print('Import successful'); caffeine=CAS('58-08-2'); print('Check Digit:', caffeine.check_digit)"

      - name: Publish to PyPI
        run: uv publish --trusted-publishing always
